/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppClickableMap {
        "activeCountries": string[] | undefined;
    }
    interface AppInfoModal {
        "countryData"?: {
    name: string,
    capital: string,
    population: number,
    flag: string
  };
    }
    interface AppMap {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppClickableMapElement extends Components.AppClickableMap, HTMLStencilElement {
    }
    var HTMLAppClickableMapElement: {
        prototype: HTMLAppClickableMapElement;
        new (): HTMLAppClickableMapElement;
    };
    interface HTMLAppInfoModalElement extends Components.AppInfoModal, HTMLStencilElement {
    }
    var HTMLAppInfoModalElement: {
        prototype: HTMLAppInfoModalElement;
        new (): HTMLAppInfoModalElement;
    };
    interface HTMLAppMapElement extends Components.AppMap, HTMLStencilElement {
    }
    var HTMLAppMapElement: {
        prototype: HTMLAppMapElement;
        new (): HTMLAppMapElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-clickable-map": HTMLAppClickableMapElement;
        "app-info-modal": HTMLAppInfoModalElement;
        "app-map": HTMLAppMapElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppClickableMap {
        "activeCountries": string[] | undefined;
        "onCountryClick"?: (event: CustomEvent<string>) => void;
    }
    interface AppInfoModal {
        "countryData"?: {
    name: string,
    capital: string,
    population: number,
    flag: string
  };
    }
    interface AppMap {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-clickable-map": AppClickableMap;
        "app-info-modal": AppInfoModal;
        "app-map": AppMap;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-clickable-map": LocalJSX.AppClickableMap & JSXBase.HTMLAttributes<HTMLAppClickableMapElement>;
            "app-info-modal": LocalJSX.AppInfoModal & JSXBase.HTMLAttributes<HTMLAppInfoModalElement>;
            "app-map": LocalJSX.AppMap & JSXBase.HTMLAttributes<HTMLAppMapElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
